language: node_js
node_js: 
  - lts/*
services: postgresql
# test:
#   adapter: postgresql
#   database: palette_picker_test
before_script:
  - psql -c 'CREATE DATABASE palette_picker_test;' -U postgres
  - knex migrate:latest --env=test
  - knex seed:run --env=test
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls